### ISSUE TITLE
pip install tamper fails on windows (pip install works otherwise)

### ISSUE THREAD

**Issue by SgtPooki** [dutzi/tamper#10]
Chrome: Version 38.0.2125.101 m
Windows OS: 8.1
## pip.log:

c:\python\Scripts\pip3 run on 10/14/14 19:25:05
Downloading/unpacking tamper
  Getting page https://pypi.python.org/simple/tamper/
  URLs to search for versions for tamper:
- https://pypi.python.org/simple/tamper/
  Analyzing links from page https://pypi.python.org/simple/tamper/
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.10.macosx-10.9-intel.exe#md5=536fad086837b19def97f5a97b2f64cb (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.11.macosx-10.9-intel.exe#md5=19d1c8f8f5c34d372b61ba7a570dfa19 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.12.macosx-10.9-intel.exe#md5=b38c08843afbde2b7f8aaa7946060db0 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.22.macosx-10.9-intel.exe#md5=5653e17c43e18005457cd093eabfdbfb (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.23.macosx-10.9-intel.exe#md5=649e5c41c82da1c85744b17589a10c57 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.3.macosx-10.9-intel.exe#md5=e1c47b9146b50328ccbd64f120884ff3 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.4.macosx-10.9-intel.exe#md5=1410c0b8fc7958736afca81792f8eede (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.5.macosx-10.9-intel.exe#md5=d61ef85b391057c5908b319940f05d90 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.6.macosx-10.9-intel.exe#md5=4c7e22258e63ef7a5a13faefbdb3822f (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.7.macosx-10.9-intel.exe#md5=f462a1da4304f2a18b07743244d3f621 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.8.macosx-10.9-intel.exe#md5=a328cc9e9aec7528d924c3e3072f29ae (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/any/t/tamper/tamper-0.9.macosx-10.9-intel.exe#md5=1abcc4a76822c683d960060884e49797 (from https://pypi.python.org/simple/tamper/); unknown archive format: .exe
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.10.tar.gz#md5=fc5c54d92530405530d14bf5568d872b (from https://pypi.python.org/simple/tamper/), version: 0.10
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.11.tar.gz#md5=18db2b49ee825114905b2abd82e80905 (from https://pypi.python.org/simple/tamper/), version: 0.11
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.12.tar.gz#md5=ad80ff52a1306f3580d7ae7efe610b75 (from https://pypi.python.org/simple/tamper/), version: 0.12
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.22.tar.gz#md5=f4f11bcc9a5b27cfd015f05fe641a67b (from https://pypi.python.org/simple/tamper/), version: 0.22
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.23.tar.gz#md5=dc6e9ff0c82d112d0555cff98860053f (from https://pypi.python.org/simple/tamper/), version: 0.23
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.3.tar.gz#md5=200f88602ebd7fd0c88db1fcfda80041 (from https://pypi.python.org/simple/tamper/), version: 0.3
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.4.tar.gz#md5=45809a51da76985a3d9e4ca1118e9417 (from https://pypi.python.org/simple/tamper/), version: 0.4
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.5.tar.gz#md5=938ac695b5bfa4e9b3544a1c49d11b9c (from https://pypi.python.org/simple/tamper/), version: 0.5
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.6.tar.gz#md5=6f096e19eddeb42eb1e234eba6d61519 (from https://pypi.python.org/simple/tamper/), version: 0.6
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.7.tar.gz#md5=40d21407364f7e5c50eac75f417a74ed (from https://pypi.python.org/simple/tamper/), version: 0.7
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.8.tar.gz#md5=7c456065f9469e52018f08c337a3d5c5 (from https://pypi.python.org/simple/tamper/), version: 0.8
    Found link https://pypi.python.org/packages/source/t/tamper/tamper-0.9.tar.gz#md5=b5fbe8542765a55488a9fafd037abe54 (from https://pypi.python.org/simple/tamper/), version: 0.9
  Using version 0.23 (newest of versions: 0.23, 0.22, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3)
  Downloading tamper-0.23.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/t/tamper/tamper-0.23.tar.gz#md5=dc6e9ff0c82d112d0555cff98860053f (from https://pypi.python.org/simple/tamper/)
  Running setup.py (path:C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey\tamper\setup.py) egg_info for package tamper
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey\tamper\setup.py", line 51
        print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'
                                                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  
  File "<string>", line 17, in <module>
  
  File "C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey\tamper\setup.py", line 51
  
    print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'
  
  ```
                                                        ^
  ```

SyntaxError: invalid syntax

---

Cleaning up...
  Removing temporary dir C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey...
Command python setup.py egg_info failed with error code 1 in C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey\tamper
Exception information:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\python\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\python\lib\site-packages\pip\req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "C:\python\lib\site-packages\pip\req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\python\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in C:\Users\RUSSEL~1\AppData\Local\Temp\pip_build_Russell Dempsey\tamper

**Comment by Nek** [comment]
Has the same error including this loop:
'''
connecting to proxy
Disconnected
'''
Tried to run tamper.py from command line and this gives me:
'''
s   {"msg": {"errorCode": 101, "errorDesc": "Could not start proxy, error loading libraries", "method": "proxy-error"}}
'''

**Comment by johim** [comment]
Try removing pydivert and install 1.0.2. I had the same issue
pip install pydivert==1.0.2

**Comment by johim** [comment]
btw, I'm having the same issue as luanvuvt. Cannot run Tamper. When I manually run temper.bat it runs OK.

Any ideas?
