### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by EnergyFusion** [dutzi/tamper#42]
Install fails with the following error:
```
Collecting tamper
  Using cached tamper-0.24.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-o8okyiji/tamper/setup.py", line 60
        print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'
                                                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o8okyiji/tamper/
```

**Comment by nonnymoose** [comment]
Same here...

The weirdest part is what happens when I run it in python:
```
>>> manifestFilename="test"
>>> print '\nWriting chrome native messaging manifest file (' + manifestFilename + ')'

Writing chrome native messaging manifest file (test)
>>> 
```

**Comment by nonnymoose** [comment]
Okay, @EnergyFusion I think I found the problem. I'm assuming you're on a linux system; if so, use your package manager to install `python-pip`. (`sudo apt install python-pip` on Debian/Ubuntu) If you have `python3-pip` installed, but not the python2 version, it *will* override the pip command! (If it still doesn't work, substitute `pip2`for `pip`.

**Comment by EnergyFusion** [comment]
Obviously! Thank you! my pip was defaulting to python3 (and pip3 was also defaulting to python3 even though i have pip2 installed) for some reason so I had to figure out what was going on with my setup.. thanks for the nudge in the right direction!

**Comment by EnergyFusion** [comment]
Now i get an error when i try install the chrome extension.. it says: 

> Invalid manifest

**Comment by nonnymoose** [comment]
@EnergyFusion That's been "quickfixed" in #35.
You can mark the issue as solved by hitting the gray "Comment and Close" when you comment.

**Comment by EnergyFusion** [comment]
Thanks!
