### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by edorgeville** [dutzi/tamper#6]
As [reported](https://www.reddit.com/r/webdev/comments/2j1mwy/i_made_a_chrome_extension_that_lets_you_inspect/cl7nu92) by [/u/thefinn93](reddit.com/u/thefinn93) : 

> error: [Errno 2] No such file or directory: '/home/finn/Library/Application
> Support/Google/Chrome/NativeMessagingHosts/'

**Comment by jkubrynski** [comment]
@dutzi It's really looooong weekend :) When can we expect Linux version?

**Comment by ledbruno** [comment]
Still doesn´t work in linux. Have a lot of trouble installing Python stuff. Trying to load unpacked expension gives me the error => Failed to load extension from: ~/dev/tamper/chrome-extension/app
Could not find key specification for 'command[1].suggested_key': Either specify a key for 'linux', or specify a default key.

Trying to install from chrome app store, there is a problem with Manifest file.

**Comment by ledbruno** [comment]
Adding "linux": "Ctrl+Shift+P" to commands entry (in the manifest.json) solves the problem.

But anyway, the pip install tamper part, is missing some required dependencies like libjpeg,xptah,sll and others. I had that problem in Ubuntu 15.10 64-bit
